name: Test, Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

#on:
#  pull_request:
#    types: [closed]
env:
  PIMS_VERSION: 2.0.0

jobs:
  build-test:
#    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: release.zip
          exclusions: '*.git* /*node_modules/* .editorconfig /*storage/*'



      - name: Upload site content
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: release.zip
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: add add version to release
        run: |
          echo "version: ${{env.PIMS_VERSION}}" > version-info
          echo "build: ${{ steps.date.outputs.date }}.${{ github.run_number }}" > version-info
          zip ./release.zip version-info

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: v${{env.PIMS_VERSION}}_${{ steps.date.outputs.date }}.${{ github.run_number }}
          tag_name: ${{ steps.date.outputs.date }}.${{ github.run_number }}

      - name: Upload asset to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
          asset_path: ./release.zip
          asset_name: pimsv2_release.zip
          asset_content_type: application/zip