name: Test and Build [Pre-PR]

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run:
          cat storage/test.js
#      - name: Attempt to fail
#        run: exit 1