name: Test and Build [Pre-PR]
env:
  TARGET_BRANCH: develop
on:
  pull_request:
    branches:
      - ${{env.TARGET_BRANCH}}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run:
          cat storage/test.js