name: Test and Build [Pre-PR]
env:
  TARGET_BRANCH: develop
on:
  pull_request:
    branches:
      - develop
jobs:
  pr-build-test:
    - name: Try to fail
      run: exit 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run:
          cat storage/test.js