name: Test and Build [Pre-PR]

on:
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2