# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - plin-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WEBAPP: plin-deploy
  GROUP: plin-test-rg
  ACCOUNT: myssstorage02
  CONTAINER: publicc
  EXPIRY_TIME: 30 minutes
  ZIP_URL: https://myssstorage02.blob.core.windows.net/publicc/php-app1.zip
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: php-app.zip

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}