# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - plin-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WEBAPP: plin-deploy

jobs:
  build-project:
    name: Build pims v2 project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Install NPM dependencies
#        run: npm install
#      - name: Build project assets
#        run: npm run build

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: pimsv2.zip
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload site content
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: pimsv2.zip
          retention-days: 1

#  distribute-project:
#    name: Distribute pims v2 project to GitHub Releases
#    runs-on: ubuntu-latest
#    needs: build-project
#    steps:
#      - name: Download site content
#        uses: actions/download-artifact@v2
#        with:
#          name: site-build
#
#      - name: Create GitHub release
#        id: create-new-release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v${{ github.run_number }}
#          release_name: Release ${{ github.run_number }}
#      - name: Upload asset to GitHub release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
#          asset_path: ./pimsv2.zip
#          asset_name: pimsv2-v${{ github.run_number }}.zip
#          asset_content_type: application/zip

  deploy-azure-containers:
    name: Deploy containers to azure
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build

      - name: deploy build through azure vm
        run: |
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          ssh -i key.pem  -o "StrictHostKeyChecking no" ${{secrets.SSH_HOST}} <<'ENDSSH'
          pwd
          rm release.zip
          curl -vLJ -H 'Authorization: token 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' -o release.zip 'https://github.com/plin-qiagen/test-php/releases/download/v33/pimsv2-v33.zip'
          curl -X POST -u '$plin-app:yA25tEcrtkiQf9eMAaoJW0i53M8od83H8MqpoSFzMC4tbnxGq3MRsdLhpbQg' https://plin-app.scm.azurewebsites.net/api/zipdeploy -T release.zip
          ENDSSH
