# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - plin-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WEBAPP: plin-deploy
  GROUP: plin-test-rg
  ACCOUNT: myssstorage02
  CONTAINER: mysccontainer02
  EXPIRY_TIME: 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: papeloto/action-zip@v1
        with:
          files: .
          dest: php-app.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: php-app.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set SAS token expiration
        run: echo "expiry=`date -u -d "$EXPIRY_TIME" '+%Y-%m-%dT%H:%MZ'`" >> $GITHUB_ENV

      - run: |
          az extension add --name webapp
          #az storage blob upload -f php-app.zip --account-name $ACCOUNT -c $CONTAINER -n php-app.zip
          ZIP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry ${{ env.expiry }} --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT | xargs)
          az webapp deploy --name $WEBAPP --resource-group $GROUP --type zip --src-url  $ZIP_URL --async false

#      - name: Azure CLI script
#        uses: azure/CLI@v1
#        with:
#          azcliversion: 2.19.1
#          inlineScript: |
#            az extension add --name webapp
#            az storage account create -n $ACCOUNT -g $GROUP -l eastus
#            az storage container create -n $CONTAINER --account-name $ACCOUNT
#            az storage blob upload -f php-app.zip --account-name $ACCOUNT -c $CONTAINER -n php-app.zip
# ZIP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry ${{ env.expiry }} --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT | xargs)
# az webapp deploy --name $WEBAPP --resource-group $GROUP --type zip --src-url  $ZIP_URL --async false

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v2
#        with:
#          name: php-app
#
#      - name: 'Deploy to Azure Web App'
#        uses: azure/webapps-deploy@v2
#        id: deploy-to-webapp
#        with:
#          app-name: 'plin-deploy'
#          slot-name: 'Production'
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5AC9E6AA8C5C412D99397240A7B2045A }}
#          package: .
