name: Build and Release [Official]
on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Release Version'
        default: 1.0.0
        required: true
env:
  RELEASE_NAME: PIMSV2
  RELEASE_FILE: pimsv2
  BUILD_TYPE: PRD
jobs:
  build-test:
    name: Build x Test [Branch ${GITHUB_REF##*/}]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: release.zip
          exclusions: '*.git* /*node_modules/* .editorconfig /*storage/*'

      - name: Upload site content
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: release.zip
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: site-build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: add add version to release
        run: |
          echo "${{env.RELEASE_NAME}} version: ${{github.event.inputs.RELEASE_VERSION}}" > version-info
          echo "build: ${{ steps.date.outputs.date }}.${{ github.run_number }}" >> version-info
          echo "sha: ${{ github.sha }}" > version-info
          echo "ref: ${{ github.ref }} > version-info

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release.zip
            version-info

#      - name: Create GitHub release
#        id: create-new-release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          release_name: ${{env.BUILD_TYPE}} ${{steps.date.outputs.date}}_${{github.run_number}}
#          tag_name: ${{env.BUILD_TYPE}}_${{steps.date.outputs.date}}_${{github.run_number}}
#          draft: true
#          prerelease: true
#      - name: Upload asset to GitHub release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
#          asset_path: ./release.zip
#          asset_name: ${{env.RELEASE_FILE}}.zip
#          asset_content_type: application/zip