name: test github action

on:
  workflow_dispatch:

env:
  PIMS_VERSION: 2.0.0

jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "branch: ${GITHUB_REF##*/} (commit ${GITHUB_SHA::8}"

      - name: Test with environment variables
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
        run: |
          echo $PIMS_VERSION - $TAG_NAME - $RELEASE_NAME

      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: ${{env.PIMS_VERSION}}- ${{ steps.date.outputs.date }}
